### ISSUE TITLE
Prepare baseline model

### ISSUE THREAD

**Issue by tschaffter** [data2health/covid19-challenge#11]
- [x] Create GH repo with codebase of the baseline method
- [x] Create README as a tutorial (see this [example](https://github.com/Sage-Bionetworks/metadata-automation-challenge) from the Metadata Automation DREAM Challenge)
- [x] Make the repo publicly accessible

**Comment by yy6linda** [comment]
Updates: around 20 predictors (including vital signs, demographics features, and clinical symptoms)are selected from the literature. Need to wait till have COVID  OMOP synpuf v6.0 data and vocabulary lists to build the feature set and the baseline model. I will complete the tutorial once the baseline model is ready.

**Comment by yy6linda** [comment]
Here is a medRxiv research on predicting patients COVID status by using ~30 features [link](https://www.medrxiv.org/content/10.1101/2020.03.19.20039099v1)
Feature Type | Examples
-- | --
Demographics(2) | Age,gender
Vital sign(4) | temperature , heart rate
Clinical sign and symbols(17) | Fever, cough, muscle ache...
Infected related biomarkers(2) | C-reactive protein, interleukin-6
Other(1) | Days from illness onset to the first admission

**Comment by yy6linda** [comment]
The baseline model is created and saved in the github repository: [link](https://github.com/yy6linda/COVID_diagnosis_baseline). I am still working on updating the wiki page.

**Comment by tschaffter** [comment]
## Update

- Waiting on the data to come up with a "better" model
- Functional model already available

**Comment by tschaffter** [comment]
The example method for Challenge Question is available [here](https://github.com/DREAMChallenges/ehr-dream-challenges/tree/master/examples/covid19-question-1).
