### ISSUE TITLE
Update example model in Q1 to support training

### ISSUE THREAD

**Issue by tschaffter** [data2health/covid19-challenge#113]
## Depends on

- #109

**Comment by yy6linda** [comment]
The baseline model that supports training is ready and yields PRAUC 0.13, ROCAUC 0.61. Currently I am working on dockerizing it and later I will submit it to test the challenge pipeline.

**Comment by tschaffter** [comment]
@yy6linda We need to update the example on GitHub to illustrate how to submit the following submissions: 1) training + evaluation and 2) evaluation only. Please create a Pull Request. Let me know if you have any question.

**Comment by tschaffter** [comment]
Done
