### ISSUE TITLE
Upgrading SynPuf

### ISSUE THREAD

**Issue by tschaffter** [data2health/covid19-challenge#17]

**Comment by tschaffter** [comment]
## Update

- Tim mentioned that synthetic data is ready
- Yao will review to check that the data are not leaking information
- Tim and Tom to use the synthetic data to test the infrastructure

**Comment by trberg** [comment]
Synthetic data has been created, validated, and [posted to synapse](https://www.synapse.org/#!Synapse:syn22043931).
