### ISSUE TITLE
Data contributor pdf

### ISSUE THREAD

**Issue by tschaffter** [data2health/covid19-challenge#21]
- [x] Invite data contributors and explain to them what to expect and how to proceed
- [x] Add to the challenge site

**Comment by trberg** [comment]
## Update
pdf has been uploaded to synapse and linked in the "Data Contributor" section of the stage site.

**Comment by tschaffter** [comment]
Link to the PDF added to the section Challenge Data on the Home page.
https://www.synapse.org/#!Synapse:syn21849256/wiki/601866
