### ISSUE TITLE
Update page Literature Review

### ISSUE THREAD

**Issue by tschaffter** [data2health/covid19-challenge#24]
Remove content and add pointer to useful resources (Justing mentioned a bioRxiv page)

**Comment by tschaffter** [comment]
@trberg Do you know what bioRxiv page Justin was talking about?

**Comment by trberg** [comment]
No, I think there are bioarxiv channels or feeds you can follow. I've never
worked with them before though

**Comment by tschaffter** [comment]
https://www.synapse.org/#!Synapse:syn21849256/wiki/601874
