### ISSUE TITLE
Prepare for accepting submissions for different questions

### ISSUE THREAD

**Issue by tschaffter** [data2health/covid19-challenge#34]
- [x] Tom to create and configure submission queue "COVID-19 DREAM Challenge: Question 1"
- [x] Thomas to reorg baseline method GH repo to store examples for different questions

**Comment by thomasyu888** [comment]
Will the different questions have different scoring and validation?

**Comment by tschaffter** [comment]
They could both be different. With potentially 10 different questions, the
output file may be different and so would be the scoring script.

**Comment by thomasyu888** [comment]
To fully simulate, I will create a different workflow per challenge question.  For now I will use the same validation and scoring function

**Comment by tschaffter** [comment]
Done
