### ISSUE TITLE
Smoke testing infra before grand opening

### ISSUE THREAD

**Issue by tschaffter** [data2health/covid19-challenge#35]
During our weekly call on Monday, we will test

## Initial test
- Test submission to Challenge Question 1 - UW Dataset - version 1
  - [x] Submission successfully evaluated
  - [x] Sub shows up in Dashboard
  - [x] Sub shows up in Leaderboard for Challenge Question 1 - UW Dataset - version 1

## Create new Challenge Question 2 - UW Dataset Y* - version 1
- Test submission to Challenge Question 2 - UW Dataset - version 1
  - [ ] Submission successfully evaluated
  - [ ] Sub shows up in Dashboard
  - [ ] Sub shows up in Leaderboard for Challenge Question 2 - UW Dataset - version 1

## "Simulate" new UW Dataset version
- Test submission to Challenge Question 1 - UW Dataset - version 2
  - [ ] Submission successfully evaluated
  - [ ] Sub shows up in Dashboard
  - [ ] Sub shows up in Leaderboard for Challenge Question 1 - UW Dataset - version 2
- "Simulate" new UW Dataset version

## More

- [x] Identify how to support / organize different datasets for different questions (yet more than one questions could use the same dataset)
- [x] Identify and set max runtime (on NCATS and UW)

**Comment by thomasyu888** [comment]
```
Add to NCAT's docker-compose .env
{'9614502': 'syn22076995', '9614503': 'syn22076996'}
Add to UW's docker-compose .env
{'9614504': 'syn22076997', '9614505': 'syn22076998'}
Make sure you run
git add infrastructure/2_workflow.cwl
git add infrastructure/2_internal_workflow.cwl
```
