### ISSUE TITLE
Identify and document datasets

### ISSUE THREAD

**Issue by tschaffter** [data2health/covid19-challenge#4]
https://www.synapse.org/#!Synapse:syn21849256/wiki/601866

**Important**: Do not post sensitive information about the datasets here (public GitHub repo)

**Comment by tschaffter** [comment]
## Update

- Dataset is ready including the gold standard
- Yao to do a second pass
- Not yet on the server

**Comment by trberg** [comment]
Dataset is ready and uploaded to the server.
Goldstandard is prepared and uploaded to synapse.
Data dictionary is prepared and uploaded to synapse.
Documentation about the data dictionary is written and posted.
Table format descriptions have been improved on the wiki data format site.
