### ISSUE TITLE
Create a page that aggregates COVID-19 related resources

### ISSUE THREAD

**Issue by tschaffter** [data2health/covid19-challenge#6]
- data
- other challenges we know of (i’ve seen stuff through Kaggle, Devpost, MIT, and maybe others)

**Comment by thomasyu888** [comment]
https://github.com/soroushchehresa/awesome-coronavirus/blob/master/README.md

**Comment by tschaffter** [comment]
Mike:
> There has been some suggestion that blood type may be linked to disease severity so I suspect modelers will be interested in using as a feature (https://www.medrxiv.org/content/10.1101/2020.03.11.20031096v2.full.pdf).

**Comment by thomasyu888** [comment]
Could we pull request into awesome-coronavirus under the "hackathon" topic?  I see that IBM has a public resource there.

This would raise awareness for our challenge as well.

**Comment by tschaffter** [comment]
@thomasyu888 This is a good idea. Let's do that once the challenge is live.

**Comment by tschaffter** [comment]
https://www.synapse.org/#!Synapse:syn21849256/wiki/601874
