### ISSUE TITLE
Add Institution and Email to the list `Looking for members?`

### ISSUE THREAD

**Issue by tschaffter** [data2health/covid19-challenge#75]
This information is included in the list `Registered Participants`. The same info should be included to the list `Looking for members? so it becomes easier to contact a potential future team mate.

See page [Participants & Teams](https://www.synapse.org/#!Synapse:syn21849256/wiki/601877)

**Comment by thomasyu888** [comment]
This is a platform issue. I can file a jira.

**Comment by thomasyu888** [comment]
https://sagebionetworks.jira.com/browse/CHALLENGE-209

**Comment by tschaffter** [comment]
This feature is now tracked by Sage in JIRA.
